### ISSUE TITLE
Inline Buttons - Can't get them to work

### ISSUE THREAD

**Issue by mkumpf** [Andries-Smit/DataGridExtention#5]
Andries

I have not been able to get the inline buttons to work.  I am trying to put in a button so that users can delete a row in a datagrid.  I have tried 2 or 3 different columns, made the columns editable, etc. but the column contents are not replaced with the button.  Can you give me some pointers about what I may be doing wrong?  I am on Mendix 5.15.

Thanks,

Mike Kumpf

**Comment by Andries-Smit** [comment]
Good Morning Mike, 

Please check the sample project in the repository. The inline buttons should be working fine with Mx 5.15. I just verified that they also work in combination with editable columns.

However, when your  ‘Flex header’, which allows you to hide and reorder columns. This might conflict with the inline buttons because the buttons are place inside the grid based on a column index (not a name). Hiding columns or reordering them can lead to unexpected behaviour. My recommendation to not use the ‘Flex header’ option in combination with inline buttons.

I could try to update the function, in such a way, that the inline buttons are placed based on the original order, but I don’t expect an update soon.

So if there is an issue with the widget; I comment to use Chrome dev tools and ‘Pause on uncaught exception’. Than trace back in the call stack in which place of the widget this issue is caused by. With those details or with a sample project I can help you out.

Kind regards, Andries
