### ISSUE TITLE
The widget does not work in Mendix 6.1.0

### ISSUE THREAD

**Issue by CharlesBronzwaer** [Andries-Smit/DataGridExtention#7]
I get an error when the widget is loaded in Mendix 6.1.0.

On login the browser just shows an empty page, in the browser console i get this error:
TypeError: Cannot read property '_Contextable' of undefined(…)

Is it possible to fix this issue?

**Comment by Crow74** [comment]
We are currently working on a migration to Mendix 6.5 and also noticed that the widget currently does not work with Mendix 6.x.

It would be really lovely if the widget would be updated for Mendix 6.x. Otherwise we would need to refactor quite a number of screens to take out the widget, which would impact the user experience quite a bit.

Cheers!

**Comment by Virjanand** [comment]
Dear Andries,

Could you please update this widget for use in Mendix 6? We rely on this widget in several places. 

We tried updating it ourselves, but we got stuck at converting the EmptyTable.js where the line 
mixins: [mendix.addon._Contextable] gives errors,

we tried changing mixins to addons and mendix.addon._Contextable to mxui/addons/_Contextable.

It's probably obvious that we don't really know what we are doing. Our next step is to look at how context works in Mendix, but we hope it is 5 min work for you instead of ? days of work for us to learn all this.

Best wishes,
Virjanand

**Comment by jandelange** [comment]
Yep, after updating from 5.21 to 6.6 We have the same problem. Blank screen after login. We only use the step button.  A great feature in Master-Detail screens for checking records on a fast way. Our users are checking constantly a lot of records ( row by row ) and hate a lot of mouse-clicking.

**Comment by gcoleske** [comment]
Great widget.  Doesn't seem to work on Mendix versions 6.8.x upwards though.

**Comment by m-kikukawa** [comment]
Great widget. Doesn't seem to work on Mendix versions 7.1.x upwards though.
Are there any plans to correspond to Mendix versions 7.1.x?

**Comment by Andries-Smit** [comment]
I don't agree with the technical implementation of this widget any longer, hacking into the private API of the Mendix client. The changes to the client API cause it to crash over and over again. I will fix some of the issue but there will no further development. 

I would recommend to to use the widget in any new project.

Next update might run on Mendix 7.

**Comment by Andries-Smit** [comment]
Released: https://appstore.home.mendix.com/link/app/877/Flock-of-Birds/Data-Grid-Extension-(Flex-Headers)
